import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar,Footer } from "./components";

import "./globals.css";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Blog-Application",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className="container flex flex-col mx-auto min-h-screen">
					<Navbar />
					<div className="flex-auto">
					{children}
					</div>
					<Footer />
				</div>
			</body>
		</html>
	);
}
